// Mini-Quiz am Ende. Jede Frage hat genau eine richtige Antwort (correct = Index in options).
import type { QuizItem } from './types';

export const QUIZ: QuizItem[] = [
  {
    id: 'q-shanghai',
    q: 'Wo wurde Yao Ming geboren?',
    options: ['Peking', 'Shanghai', 'Hongkong'],
    correct: 1,
    explain: 'In Shanghai, 上海 Shànghǎi.',
    related: ['y-kindheit-1'],
  },
  {
    id: 'q-oscar',
    q: 'Welche Auszeichnung bekam Jackie Chan 2016?',
    options: ['Einen Ehren-Oscar', 'Einen Grammy', 'Eine Olympia-Medaille'],
    correct: 0,
    explain: 'Einen Ehren-Oscar für sein Lebenswerk.',
    related: ['j-karriere-3'],
  },
  {
    id: 'q-long',
    q: 'Was bedeutet 龙 lóng?',
    options: ['Tiger', 'Drache', 'Berg'],
    correct: 1,
    explain: '龙 lóng heißt Drache, ein Glückssymbol.',
    related: ['j-fun-1'],
  },
  {
    id: 'q-draft',
    q: 'An welcher Stelle wurde Yao 2002 im NBA-Draft gewählt?',
    options: ['Nr. 17', 'Nr. 5', 'Nr. 1'],
    correct: 2,
    explain: 'Die Houston Rockets wählten ihn an Nr. 1.',
    related: ['y-karriere-1'],
  },
  {
    id: 'q-panda',
    q: 'In welchem Film spricht Jackie Meister Affe?',
    options: ['Mulan', 'Kung Fu Panda', 'Rush Hour'],
    correct: 1,
    explain: 'In Kung Fu Panda, 功夫熊猫.',
    related: ['j-fun-2'],
  },
  {
    id: 'q-ganbei',
    q: 'Was bedeutet 干杯 gānbēi?',
    options: ['Danke', 'Guten Appetit', 'Prost'],
    correct: 2,
    explain: 'Wörtlich: „die Tasse leeren“, also Prost!',
  },
  {
    id: 'q-schule',
    q: 'Welche Schule besuchte Jackie als Kind?',
    options: ['Eine Peking-Oper-Schule', 'Ein Sportinternat', 'Eine Militärakademie'],
    correct: 0,
    explain: 'Die China Drama Academy, eine Schule der Peking-Oper.',
    related: ['j-kindheit-2'],
  },
  {
    id: 'q-groesse',
    q: 'Wie groß ist Yao Ming?',
    options: ['1,98 m', '2,29 m', '2,50 m'],
    correct: 1,
    explain: '2,29 Meter, das sind 7 Fuß 6 Zoll.',
    related: ['y-person-2'],
  },
  {
    id: 'q-cha',
    q: 'Was bedeutet 茶 chá?',
    options: ['Reis', 'Wasser', 'Tee'],
    correct: 2,
    explain: '茶 chá ist Tee, der Star dieses Hauses.',
  },
  {
    id: 'q-xiexie',
    q: 'Was bedeutet 谢谢 xièxie?',
    options: ['Danke', 'Bitte', 'Entschuldigung'],
    correct: 0,
    explain: '谢谢 xièxie heißt danke.',
  },
  {
    id: 'q-fahne',
    q: 'Was durfte Yao 2004 und 2008 bei den Olympischen Spielen tragen?',
    options: ['Die Fackel', 'Die Fahne Chinas', 'Die Goldmedaille'],
    correct: 1,
    explain: 'Die Fahne Chinas, 国旗 guóqí.',
    related: ['y-china-1'],
  },
  {
    id: 'q-stiftung',
    q: 'Seit wann gibt es Jackies Stiftung in Hongkong?',
    options: ['Seit 1988', 'Seit 2016', 'Seit 1954'],
    correct: 0,
    explain: 'Die Jackie Chan Charitable Foundation wurde 1988 gegründet.',
    related: ['j-engage-1'],
  },
];
