// Aussehen aller Figuren im bisherigen stilisierten Look. Gäste, Teemeister und Spielfigur haben generische
// Gesichter. Jackie Chan und Yao Ming sind ihren Vorbildern nachempfunden (Gesichtsform, Augen, Brauen, Nase,
// Lächeln, Frisur, Körperbau), ohne Karikatur; Kleidung und Stil bleiben wie bisher.
import type { Look } from './character';

/** Spielfigur: vier neutrale Outfits zur Auswahl */
export const PLAYER_LOOKS: (Look & { label: string; swatch: string })[] = [
  {
    id: 'player',
    label: 'Jade',
    swatch: '#2e7d6b',
    height: 1.72,
    headRatio: 0.19,
    build: 1,
    skin: '#e8b994',
    hair: '#2a1d15',
    hairStyle: 'side',
    hairModel: [{ piece: 'Hair_SimpleParted', scale: [1.06, 1.02, 1.04] }],
    top: { color: '#2e7d6b', gold: '#e6c27a', motif: 'hem', skirt: 0.18, trim: '#e6c27a' },
    cuff: '#efe4cc',
    pants: { color: '#e9dfc8' },
    belt: { color: '#8a5a2a' },
    shoes: { color: '#5a3a24', sole: '#2a1d15' },
  },
  {
    id: 'player',
    label: 'Indigo',
    swatch: '#2f3f7a',
    height: 1.7,
    headRatio: 0.19,
    build: 0.97,
    skin: '#d9a47c',
    hair: '#16110e',
    hairStyle: 'ponytail',
    top: { color: '#2f3f7a', gold: '#d9c38a', motif: 'cloud', skirt: 0.3, trim: '#d9c38a' },
    pants: { color: '#4a4a52' },
    belt: { color: '#b3261a', tassels: true },
    shoes: { color: '#f0ece2', sole: '#d6d0c2', stripe: '#2f3f7a' },
  },
  {
    id: 'player',
    label: 'Ocker',
    swatch: '#c08a3a',
    height: 1.76,
    headRatio: 0.19,
    build: 1.04,
    skin: '#c98d68',
    hair: '#241912',
    hairStyle: 'straw',
    top: { color: '#c08a3a', gold: '#6b3a1a', motif: 'hem', skirt: 0.22, trim: '#6b3a1a' },
    cuff: '#f0e6cf',
    pants: { color: '#5a4636', wide: true },
    belt: { color: '#3a2a1e' },
    shoes: { color: '#3a2a1e', sole: '#1c140e' },
  },
  {
    id: 'player',
    label: 'Pflaume',
    swatch: '#7a3150',
    height: 1.66,
    headRatio: 0.185,
    build: 0.95,
    skin: '#efc6a6',
    hair: '#3a2418',
    hairStyle: 'bun',
    hairModel: [{ piece: 'Hair_Buns', scale: [1.04, 1.02, 1.04] }],
    top: { color: '#7a3150', gold: '#e8c37a', motif: 'cloud', skirt: 0.62 },
    inner: { color: '#f3e8d8' },
    pants: { color: '#3a2a35' },
    belt: { color: '#e8c37a' },
    shoes: { color: '#7a3150', sole: '#2a1a22' },
  },
];

/** Jackie Chan: deutlich kleiner, dunkle Kampfkunst-Jacke mit Goldstickerei, helle Ärmelaufschläge, Drachen-Hose */
export const JACKIE_LOOK: Look = {
  id: 'jackie',
  height: 1.74,
  headRatio: 0.18,
  build: 1.0,
  skin: '#e2ae84',
  hair: '#17110d',
  hairStyle: 'sweep',
  // dichte, lockere Haare mit seitlich fallendem Pony
  hairModel: [{ piece: 'Hair_SimpleParted', scale: [1.08, 1.02, 1.06], offset: [0, 0, -0.02] }],
  keepDrawnHair: true,
  // breites, rundliches Gesicht, volle Wangen, weicher kräftiger Kiefer, kleine lebhafte Augen mit Lachfältchen,
  // gerade dichte Brauen, breiterer Nasenrücken mit runder Spitze, breites schiefes Lächeln, abstehende Ohren
  face: {
    skull: [1.04, 1.0, 0.97],
    jaw: 0.9,
    jawW: 0.95,
    jawH: 0.62,
    chin: 0.6,
    chinW: 1.1,
    cheekbones: 0.4,
    cheeks: 0.9,
    eyeW: 0.88,
    eyeH: 0.56,
    eyeGap: 0.37,
    eyeY: 0.04,
    iris: '#3a2214',
    smileEyes: 0.6,
    laughLines: 0.9,
    browThick: 1.25,
    browLen: 1.1,
    browTilt: 0.04,
    browY: 0.3,
    browArch: 0.3,
    noseW: 1.3,
    noseH: 1.05,
    noseTip: 1.2,
    noseBridge: 0.5,
    noseWings: 0.9,
    mouthW: 1.3,
    smirk: 0.6,
    lip: 0.6,
    mouthY: -0.4,
    earSize: 1.15,
    earOut: 0.45,
    foreheadLines: 0.5,
    blush: 0.2,
  },
  top: {
    color: '#1f2433',
    gold: '#e0b04f',
    motif: 'cloud',
    skirt: 0.14,
    trim: '#e0b04f',
    sleeveMotif: 'hem',
  },
  cuff: '#f4eee2',
  pants: { color: '#262a36', wide: true, motif: 'dragon', gold: '#d9a94a' },
  belt: { color: '#b3261a', tassels: true },
  shoes: { color: '#f4f1ea', sole: '#d9d4c8', stripe: '#b3261a' },
};

/** Yao Ming: 2,29 m, breite Schultern, langer roter Mantel mit Golddrachen, helles Hemd mit Knotenknöpfen, Basketball */
export const YAO_LOOK: Look = {
  id: 'yao',
  height: 2.29,
  headRatio: 0.142,
  build: 1.1,
  shoulders: 1.1,
  legRatio: 0.47,
  armRatio: 1.07,
  handScale: 1.3,
  footScale: 1.25,
  skin: '#dfac83',
  hair: '#0f0d0c',
  hairStyle: 'crop',
  // sehr kurz, Seiten besonders kurz, Deckhaar minimal länger
  hairModel: [{ piece: 'Hair_Buzzed', scale: [1.03, 0.98, 1.03], offset: [0, 0.07, -0.01] }],
  // längliches, leicht rechteckiges Gesicht, hohe breite Stirn, breite Wangenknochen, flache Wangen, kräftiger
  // Kiefer und breites Kinn, schmale ruhige Augen, gerade kräftige Brauen, große Nase mit breiter Basis
  face: {
    skull: [0.95, 1.2, 0.98],
    jaw: 0.9,
    jawW: 0.95,
    jawH: 0.35,
    chin: 1.15,
    chinW: 1.4,
    cheekbones: 0.9,
    cheeks: 0,
    eyeW: 0.86,
    eyeH: 0.5,
    eyeGap: 0.38,
    eyeY: 0.08,
    iris: '#2e1c12',
    smileEyes: 0.2,
    laughLines: 0,
    browThick: 1.6,
    browLen: 1.3,
    browTilt: 0,
    browY: 0.34,
    noseW: 1.45,
    noseH: 1.25,
    noseTip: 1.35,
    noseBridge: 1.2,
    noseWings: 1.1,
    mouthW: 1.4,
    lip: 0.7,
    mouthY: -0.44,
    earSize: 1.3,
    earOut: 0.25,
    blush: 0.15,
  },
  top: { color: '#a8231a', gold: '#e3b450', motif: 'dragon', skirt: 0.58, open: true, sleeveMotif: 'hem' },
  inner: { color: '#f4eee4', knots: true },
  pants: { color: '#1f222a', wide: true },
  belt: { color: '#c42a1c', tassels: true },
  shoes: { color: '#1d1d22', sole: '#f2f0ea', stripe: '#e3b450' },
  prop: 'ball',
};

/** Der alte Teemeister: weißer Bart, Schürze, ruhige Haltung */
export const MASTER_LOOK: Look = {
  id: 'master',
  height: 1.6,
  headRatio: 0.19,
  build: 0.98,
  skin: '#e3b08c',
  hair: '#f1ede4',
  brows: '#f1ede4',
  hairStyle: 'elder',
  beard: true,
  top: { color: '#2d5a52', gold: '#d6b56a', motif: 'hem', skirt: 0.82 },
  apron: '#efe5cf',
  pants: { color: '#2a2622' },
  belt: { color: '#8a5a2a' },
  shoes: { color: '#1e1a16', sole: '#3a2a1a' },
};

/** Generische Gäste (keine realen Vorbilder) */
export const GUEST_LOOKS: Record<string, Look> = {
  boardA: {
    id: 'boardA',
    height: 1.7,
    headRatio: 0.19,
    build: 1.02,
    skin: '#d9a27a',
    hair: '#4a4038',
    hairStyle: 'cap',
    top: { color: '#5a3a28', gold: '#c9a25a', motif: 'hem', skirt: 0.55, trim: '#c9a25a' },
    pants: { color: '#2e2a26' },
    belt: { color: '#2e2a26' },
    shoes: { color: '#1e1a16', sole: '#3a2a1a' },
  },
  boardB: {
    id: 'boardB',
    height: 1.64,
    headRatio: 0.185,
    build: 0.97,
    skin: '#ecc0a0',
    hair: '#8a8580',
    hairStyle: 'crop',
    hairModel: [{ piece: 'Hair_Buzzed', scale: [1.03, 1.0, 1.03], offset: [0, 0.04, 0] }],
    top: { color: '#3c6a4a', gold: '#d9c38a', motif: 'plain', skirt: 0.2, trim: '#d9c38a' },
    pants: { color: '#3a3a40' },
    shoes: { color: '#2a2622', sole: '#121010' },
  },
  poet: {
    id: 'poet',
    height: 1.62,
    headRatio: 0.19,
    build: 0.92,
    skin: '#f0c9aa',
    hair: '#1e1612',
    hairStyle: 'bun',
    hairModel: [{ piece: 'Hair_Long', scale: [1.05, 1.02, 1.05] }],
    top: { color: '#d98c8c', gold: '#f5e3b8', motif: 'cloud', skirt: 0.85 },
    inner: { color: '#f6efe2' },
    pants: { color: '#7a4a4a' },
    belt: { color: '#2e6b5e' },
    shoes: { color: '#2e6b5e', sole: '#1a2a24' },
    prop: 'brush',
  },
  merchant: {
    id: 'merchant',
    height: 1.68,
    headRatio: 0.19,
    build: 1.18,
    skin: '#d79e76',
    hair: '#2a2420',
    hairStyle: 'cap',
    top: { color: '#7a1f2a', gold: '#e3b450', motif: 'hem', skirt: 0.7, trim: '#e3b450' },
    pants: { color: '#2a1e1a' },
    belt: { color: '#e3b450' },
    shoes: { color: '#1a1412', sole: '#3a2a1a' },
    prop: 'fan',
  },
  child: {
    id: 'child',
    height: 1.12,
    headRatio: 0.25,
    build: 1.0,
    legRatio: 0.4,
    skin: '#f2c7a4',
    hair: '#1a1410',
    hairStyle: 'kidBuns',
    hairModel: [{ piece: 'Hair_Buns', scale: [1.05, 1.03, 1.05] }],
    top: { color: '#d8452e', gold: '#f2d27a', motif: 'hem', skirt: 0.2, trim: '#f2d27a' },
    pants: { color: '#f0e2c4' },
    shoes: { color: '#d8452e', sole: '#f4efe4' },
  },
  terrace: {
    id: 'terrace',
    height: 1.58,
    headRatio: 0.19,
    build: 0.95,
    skin: '#e8b996',
    hair: '#c9c4bc',
    hairStyle: 'bun',
    hairModel: [{ piece: 'Hair_Buns', scale: [1.04, 1.02, 1.04] }],
    top: { color: '#6f6aa0', gold: '#e6d3a0', motif: 'cloud', skirt: 0.6 },
    inner: { color: '#efe8dc' },
    pants: { color: '#3c3a52' },
    shoes: { color: '#2a2838', sole: '#14121c' },
  },
};
